name: Post to Bluesky

on:
  schedule:
    #- cron: "0 11 * * 6" # 매주 토요일 11:00 UTC (= 20:00 KST)에 자동 실행
    - cron: "0 1 * * 3" # 자동 실행 테스트용
  workflow_dispatch: # "Run workflow" 버튼으로 수동 실행 가능

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Run bot
        run: npx tsx src/post.ts
        env: #계정 인증 정보는 secrets 이용
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_GID: ${{ secrets.SHEET_GID }}
